In [1]:
import cv2
import pickle as pkl
import numpy as np
import os
import csv
import time
from datetime import datetime

<h1>Take Video</h1>

In [10]:
video = cv2.VideoCapture(0)
feature_extractions = cv2.CascadeClassifier('./Data/haarcascade_frontalface_default.xml')

faces_data = []
i = 0
name = input('Enter your name: ')

while True:
    ret, frame = video.read()
    grey = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    face = feature_extractions.detectMultiScale(grey, 1.3, 5)
    
    for x,y,w,h in face:
        crop_image = frame[y:y+h, x:x+w, :]
        resized_image = cv2.resize(crop_image, (50,50))
        print(resized_image)
        if len(faces_data) <= 100 and i%10==0:
            faces_data.append(resized_image)
        i += 1
        
        cv2.putText(frame, str(len(faces_data)), (50,50), cv2.FONT_HERSHEY_COMPLEX, 2,
                    (50,50,255), 2)
        
        cv2.rectangle(frame, (x,y), (x+w, y+h), (50, 50, 255), 2)
    cv2.imshow("Camera", frame)

    k = cv2.waitKey(1)

    if k == ord('q') or len(faces_data)==100:
        break

video.release()
cv2.destroyAllWindows()

[[[176 201 232]
  [129 152 184]
  [ 98 119 153]
  ...
  [137 162 185]
  [144 171 193]
  [166 193 216]]

 [[158 181 214]
  [119 141 176]
  [101 120 157]
  ...
  [123 148 172]
  [137 164 185]
  [161 188 211]]

 [[134 156 189]
  [126 147 182]
  [ 98 116 154]
  ...
  [110 134 162]
  [130 155 181]
  [154 180 207]]

 ...

 [[204 232 255]
  [203 231 255]
  [203 231 255]
  ...
  [195 217 255]
  [195 217 255]
  [196 218 255]]

 [[204 232 255]
  [204 232 254]
  [202 230 254]
  ...
  [193 214 255]
  [195 217 255]
  [195 219 255]]

 [[205 234 255]
  [204 233 254]
  [202 232 254]
  ...
  [194 216 255]
  [195 217 255]
  [196 220 255]]]
[[[183 202 234]
  [149 164 197]
  [118 132 166]
  ...
  [103 127 156]
  [130 154 182]
  [138 163 189]]

 [[171 189 220]
  [133 149 182]
  [117 131 166]
  ...
  [ 70  94 126]
  [101 126 156]
  [125 151 179]]

 [[149 168 199]
  [134 150 183]
  [129 144 179]
  ...
  [ 58  82 116]
  [ 93 118 150]
  [118 144 174]]

 ...

 [[205 225 255]
  [204 225 255]
  [203 224 255]
  ..

In [11]:
resized_image.shape

(50, 50, 3)

In [12]:
len(faces_data)

100

In [13]:
face_data = np.asarray(faces_data)

face_data = face_data.reshape(100, -1)

In [14]:
face_data.shape

(100, 7500)

In [15]:
if 'names.pkl' not in os.listdir('Data/'):
    names = [name]*100
    with open('Data/names.pkl', 'wb') as f:
        pkl.dump(names, f)
else:
    with open('Data/names.pkl', 'rb') as f:
        names = pkl.load(f)
    names += [name]*100
    with open('Data/names.pkl', 'wb') as f:
        pkl.dump(names, f)

if 'faces_data.pkl' not in os.listdir('Data/'):
    with open('Data/faces_data.pkl', 'wb') as f:
        pkl.dump(face_data, f)
else:
    with open('Data/faces_data.pkl', 'rb') as f:
        faces = pkl.load(f)
    faces = np.append(faces, face_data, axis=0)
    with open('Data/faces_data.pkl', 'wb') as f:
        pkl.dump(faces, f)

In [16]:
with open('Data/faces_data.pkl', 'rb') as f:
    data = pkl.load(f)
    print(data)

[[118 131 140 ...  32  38  30]
 [144 159 164 ...  32  30  30]
 [171 187 193 ...  46  36  29]
 ...
 [142 153 170 ... 126 141 155]
 [124 132 154 ... 129 140 161]
 [141 150 169 ... 133 143 160]]


In [17]:
with open('Data/names.pkl', 'rb') as f:
    data = pkl.load(f)
    print(data)

['Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka', 'Caraka',

<h1>Training Using K-NN</h1>

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
with open('Data/names.pkl', 'rb') as f:
    y_train = pkl.load(f)

with open('Data/faces_data.pkl', 'rb') as f:
    X_train = pkl.load(f)

In [20]:
model_knn = KNeighborsClassifier(n_neighbors=3)

model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

<h1>Testing</h1>

In [21]:
from win32com.client import Dispatch

def speak(speaks):
    speak = Dispatch(("SAPI.SpVoice"))
    speak.Speak(speaks)

In [27]:
video = cv2.VideoCapture(0)
feature_extractions = cv2.CascadeClassifier('./Data/haarcascade_frontalface_default.xml')

col_names = ['NAME', 'DATE', 'TIME']

while True:
    ret, frame = video.read()
    grey = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    face = feature_extractions.detectMultiScale(grey, 1.3, 5)
    
    for x,y,w,h in face:
        crop_image = frame[y:y+h, x:x+w, :]
        resized_image = cv2.resize(crop_image, (50,50)).flatten().reshape(1, -1)
        output = model_knn.predict(resized_image)
        ts = time.time()
        dateTime = datetime.fromtimestamp(ts).strftime("%d-%m-%Y")
        timeStamp = datetime.fromtimestamp(ts).strftime("%H:%M:%S")
        exist = os.path.isfile('Attendance/Attendance_' + dateTime + '.csv')

        cv2.putText(frame, f'{str(output[0])}: {model_knn.predict_proba(resized_image)}', (x,y-15), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 2)
        
        cv2.rectangle(frame, (x,y), (x+w, y+h), (50, 50, 255), 2)

        attendance = [str(output[0]), str(dateTime), str(timeStamp)]
    cv2.imshow("Frame", frame)

    k = cv2.waitKey(1)
    if k == ord('o'):
        speak('Attendance Taken')
        time.sleep(5)
        if exist:
            with open('Attendance/Attendance_' + dateTime + '.csv', '+a') as f:
                writer = csv.writer(f)
                writer.writerow(attendance)
            f.close()
        else:
            with open('Attendance/Attendance_' + dateTime + '.csv', '+a') as f:
                writer = csv.writer(f)
                writer.writerow(col_names)
                writer.writerow(attendance)
            f.close()
    if k == ord('q'):
        break

video.release()
cv2.destroyAllWindows()

In [59]:
resized_image.shape

(1, 7500)